name: Update data
on:
  schedule:
    - cron: '35 11 * * *' # 6:35 PM Vietnam
  workflow_dispatch:

jobs:
  update-data:
    runs-on: ubuntu-22.04
    permissions:
      contents: write   # Cần quyền ghi để push
    steps:
      - name: checkout repo content
        uses: actions/checkout@v5
        with:
          fetch-depth: 0          # Lấy full history để tránh diverge
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: setup python
        uses: actions/setup-python@v6
        with:
          python-version: '3.11'
          cache: pip
          cache-dependency-path: requirements.txt

      - name: install python packages
        run: pip install -r requirements.txt

      - name: update data
        run: python main.py

      - name: get current date
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: "Updated ${{ env.date }}"
          commit_user_name: GitHub Action
          commit_user_email: action@github.com
          # Chỉ commit các file data (tùy chỉnh nếu cần)
          # file_pattern: 'data/*'
